---
title: Revovision
timezone: UTC
collections:
  menus:
    title: Menus
    output: true
  methodes:
    title: Methodes
    output: true
    titre: comment on bosse
    description: wdfdsg
  posts:
    title: Posts
    output: true
  realisations:
    title: Realisations
    output: true
  services:
    title: Services
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
description: Agence de Developpement Web.
permalink: pretty
favicon-image: 
meta-title: Site Web personalises
meta-description: Revovision cree des sites webs personalises a partir de designs
  personalises qui representent votre identite visuelle
logo: "/uploads/logo.png"
background-image: "/uploads/arriere.jpg"
slogan: REVOVISION
sous-slogan: Des sites webs qui vous ressemblent
texte-boutton: Services Offerts
lien-boutton: "#services"
email-contact: contact@revovision.ca
pre-footer-background-image: 
pre-footer-text-1: Gardez votre identite visuelle
pre-footer-text-2: Des sites web personalises avec une experience utilisateur hors
  du commun
pre-footer-boutton-texte: Contactez Nous
pre-footer-boutton-lien: "#footer"
footer-text: Revovision, votre integrateur de site web personalise.
