---
title: Revovision
timezone: UTC
collections:
  menus:
    title: Menus
    output: true
  methodes:
    title: Methodes
    output: true
    titre: comment on bosse
    description: wdfdsg
  posts:
    title: Posts
    output: true
  realisations:
    title: Realisations
    output: true
  services:
    title: Services
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
description: Revovision crée des sites webs personalisés à partir de designs personalisés
  qui représentent votre identité visuelle.
permalink: pretty
favicon-image: 
meta-title: Site Web personalisés
meta-description: Revovision crée des sites webs personalisés à partir de designs
  personalisés qui représentent votre identité visuelle.
logo: "/uploads/logo.png"
background-image: "/uploads/arriere.jpg"
slogan: REVOVISION
sous-slogan: Des sites webs qui vous ressemblent
texte-boutton: Services Offerts
lien-boutton: "#services"
email-contact: gaspard@revovision.ca
pre-footer-background-image: "/uploads/technlogie.jpg"
pre-footer-text-1: Gardez votre identite visuelle
pre-footer-text-2: Des sites web personalises avec une experience utilisateur hors
  du commun
pre-footer-boutton-texte: Contactez Nous
pre-footer-boutton-lien: "#footer"
footer-text: Revovision, votre intégrateur de site web personalisé.
